version: 2

sources:
  - name: staging
    database: dtc-de-375519 # bq project
    schema: cota_parlamentar_ds # bq dataset

    tables: 
      - name: cota_parlamentar_raw
      

models:
    - name: cota_parlamentar_gold
      description: >
        Data from parliamentary quotas (cotas parlamentares) sanitised and in raw state

    - name: cota_parlamentar_by_state_party
      description: >
        Parlametary quotas grouped by party and state
