# https://github.com/flavienbwk/prefect-docker-compose/tree/main/server
version: "3.7"
services:

  postgres:
    command:
      - postgres
      - -c
      - max_connections=150
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - postgres:/var/lib/postgresql/data
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 5s
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} -h localhost | grep "accepting connections" || exit 1
      timeout: 5s
    image: postgres:14
    restart: always
    #ports:
    #  - 5432:5432

    expose:
      - 5432
  orion:
    restart: always
    build: .
    command: prefect orion start
      #- |
      #- prefect orion start
      #- prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api
      #- prefect agent start -q "default"
    ports:
      - 4200:4200
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - prefect_data:/root/.prefect
      - prefect_flows:/flows
    environment:
      PREFECT_ORION_API_HOST: 0.0.0.0
      PREFECT_ORION_DATABASE_CONNECTION_URL: ${DB_CONNECTION_URL}
      PREFECT_ORION_ANALYTICS_ENABLED: "false"
      PREFECT_LOGGING_SERVER_LEVEL: WARNING
      PREFECT_API_URL: ${PREFECT_API_URL}

volumes:
  postgres:
  prefect_data:
  prefect_flows:~/dtc-de-project/flows/
